name: $(MajorVersion).$(MinorVersion).$(rev:rr)

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'

steps:
- task: UseDotNet@2
  displayName: Use .NET 6.0
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- task: DotNetCoreCLI@2
  displayName: Restore app
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'

- task: VersionDotNetCoreAssemblies@2
  displayName: 'Update version'
  inputs:
    AddDefault: true
    VersionRegex: '\d+\.\d+\.\d+'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
 
 
- task: DotNetCoreCLI@2
  displayName: 'Publish API'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/ErgoNames.Api.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish API Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)\ErgoNames.Api.zip'
    ArtifactName: Api    